dist: trusty
osx_image: xcode8.3
sudo: required
os:
  - linux
  - osx
addons:
  chrome: beta
  apt:
    packages:
      - libsecret-1-dev
      - libopenjp2-tools
      - graphicsmagick
      - xz-utils
  artifacts:
    paths:
      - $(ls build/*.zip | tr "\n" ":")
      - $(ls build/*.dmg | tr "\n" ":")
language: node_js
node_js: "8"

install:
  - yarn install
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sleep 3; fi
script:
  - yarn run ci

notifications:
  email: false

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

branches:
  only:
  - master
  - /^release\/v\d+\.\d+(\.\d+)?(-\S*)?$/
